#pagehelper分页插件配置
#pagehelper 分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql

spring:
  profiles:
    active: dev
   # JSON Serialization
  jackson.serialization.write_dates_as_timestamps: false

  freemarker:
    template-loader-path: classpath:/templates
    # 关闭缓存 上线生产环境需要改为true
    cache: false
    charset: utf-8
    content-type: text/html
    suffix: .ftl
    # 是否在model自动把session中的attribute导入进去
    expose-session-attributes: true

  http:
    converters:
      preferred-json-mapper: jackson

