server:
  port: 8081

spring:
  datasource:
    username: king
    password: 123456
    url: jdbc:mysql://db.elitescloud.com:25005/king?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: db.elitescloud.com
    port: 25007
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
    timeout: 0
    password: Xmm-5fLqAbELSw9AviWN
    database: 2


#showSql
logging:
  level:
    com:
      example:
        mapper: debug
debug: true