server:
  port: 8081


spring.datasource:
  url: jdbc:mysql://db.elitescloud.com:25005/king?useSSL=false&serverTimezone=Asia/Shanghai
  username: king
  password: 123456
  hikari:
    #指定连接池中连接的最大生存时间，
    max-lifetime: 28740000
    #指定连接的超时时间，毫秒单位.
    connection-timeout: 3000
    #指定连接多久没被使用时，被设置为空闲
    idle-timeout: 30000
    #指定连接池最大的连接数，包括使用中的和空闲的连接.
    maximum-pool-size: 10

  redis:
    host: db.elitescloud.com
    port: 25007
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
    timeout: 0
    password: Xmm-5fLqAbELSw9AviWN
    database: 2

mybatis:
  # spring boot集成mybatis的方式打印sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

#showSql
#logging:
#  level:
#    com:
#      example:
#        mapper: debug
logging:
  level:
    com.example.demo.dao : debug
debug: true